server:
    port: 9000
spring:
    application:
        name: Authorization-Server-With-Database
    cors:
        allow-credentials: true
        allowed-headers: '*'
        allowed-methods: GET, POST, PUT, DELETE
        allowed-origins: http://localhost:4200
    datasource:
        driver-class-name: org.postgresql.Driver
        password: training
        url: jdbc:postgresql://10.11.12.95:5460/training
        username: training
        hikari:
            connectionTimeout: 30000
            idleTimeout: 30000
            leak-detection-threshold: 2100
            maxLifetime: 2000000
            maximumPoolSize: 20
            minimumIdle: 1
            poolName: SpringBootJPAHikariCP
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
logging:
    level:
        root: INFO
        com.example.myapp: DEBUG
#
#  main:
#    allow-circular-references: true